matrix:
  include:
    - language: ruby
      rvm:
      - 2.6.0

      install:
        - gem install jekyll
        - gem install bundler:2.0.1
        - bundle install

      before_script:
        - chmod +x ./script/cibuild

      script: ./script/cibuild

      env:
        global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

      sudo: false
      exclude: [vendor]

