matrix:
  include:
    - language: ruby
      rvm:
      - 2.6.0

      install:
        - gem install jekyll

      before_script:
        - chmod +x ./script/cibuild
        - bundle update bundler

      script: ./script/cibuild

      env:
        global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

      sudo: false
      exclude: [vendor]

