# Site settings
title: Kevin Fronczak Custom Designs
copyright: Kevin Fronczak
email: kfronczak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Adventures in woodworking and makin' stuff. 
baseurl:  # the subpath of your site, e.g. /blog/
homeurl: https://kevinfronczakdesigns.com/
url:  https://kevinfronczakdesigns.com # the base hostname & protocol for your site
logo: "/img/logos/logo-full.png"
instagram_username: kevin_fronczak
github_username:  fronzbot

plugins:
  - jekyll-paginate
  - kramdown
  - jekyll-assets
# Build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed

assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "*.jpg"
  source:
    - assets/fonts
    - img
  features:
    automatic_img_size: true
    automatic_img_alt: true

collections:
  portfolio:
    output: true
    mainnav: true
    permalink: /portfolio/:path/
    url: /portfolio/
    class: main-portfolio
    order: 1
  shopbuilds:
    output: true
    mainnav: true
    permalink: /shopbuilds/:path/
    url: /shopbuilds/
    class: main-shopbuilds
    order: 2
  plans:
    output: true
    mainnav: true
    permalink: /plans/:path/
    url: /plans/
    class: main-plans
    order: 3
  about:
    output: true
    mainnav: false
    permalink: /:path/
    url: /about/
