# Site settings
title: Kevin Fronczak
email: kfronczak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Adventures in woodworking and makin' stuff. 
baseurl:  # the subpath of your site, e.g. /blog/
homeurl: https://fronczakwoodworks.com/
url:  https://fronczakwoodworks.com # the base hostname & protocol for your site
instagram_username: kevin_fronczak
twitter_username: fronzbot
youtube_username: kevinfronczak
github_username:  fronzbot

plugins:
  - jekyll-paginate
  - kramdown
  - jekyll-assets

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed

assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "*.jpg"
  source:
    - assets/fonts
    - img
  features:
    automatic_img_size: true
    automatic_img_alt: true

collections:
  furniture:
    output: true
    permalink: /furniture/:path/
  shopbuilds:
    output: true
    permalink: /shopbuilds/:path/
  plans:
    output: true
    permalink: /plans/:path/
